# Site settings
title: Ant Blog
SEOTitle: Ant Blog
header-img: img/home-bg.jpg
email: namduhyun87@gmail.com
description: ""
keyword: "Nam, Ant, Duhyun, iOS, Develop, Swift, RxSwift, Objective-C, xcode, apple, iPhone, Mac"
url: "https://dragonfly8714.github.io"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'



# SNS settings
RSS: false
#weibo_username:
#zhihu_username:
github_username:    dragonfly8714
#twitter_username:
#facebook_username:
#linkedin_username:  firstname-lastname-idxxxx



# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`
timezone: KO  



# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins: [jekyll-paginate]



# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important
  syntax_highlighter_opts:
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1



# Disqus settings
disqus_username: dragonfly8714-github-io
# Netease settings
netease_comment: false



# Analytics settings
# Baidu Analytics 
#ba_track_id: [your track id]
# Google Analytics
ga_track_id: 'UA-197437137-1'            # Format: UA-xxxxxx-xx
ga_domain: dragonfly8714.github.io



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "Nam Duhyun<br>iOS Developer"
sidebar-avatar: /img/nam_profile.jpeg      # use absolute URL, seeing it's used in both `/` and `/about/`



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value



# Progressive Web Apps
chrome-tab-theme-color: "#000000"
service-worker: true
# MathJax rendering for layout:page (e.g. post preview)
page-mathjax: false
adsense: "disabled"
adsense-data-ad-client: "ca-pub-1239205227676276"
adsense-data-ad-slot: "5015776274"
